general:
  mqtt_host: "localhost"
  mqtt_port: 1883
  mqtt_username: "mqtt_user"
  mqtt_password: "mqtt_password"
  mqtt_application_name: "car_detection_app"

services:
  generators:
    id_prefix: "generator"
    outgoing_topic: "testapp/generator"
    instances:
    - id: "1"
      data_source: 0
      priority: 1
      tuned_parameters:
        resolution: 800
        fps: 10
        encoding: "h264"
        frames_per_task: 10
        skipping_frame_interval: 10

    - id: "2"
      data_source: 0
      priority: 2
      tuned_parameters:
        resolution: 800
        fps: 10
        encoding: "h264"
        frames_per_task: 5
        skipping_frame_interval: 20

  processors:
    - order: 1
      id_prefix: "processor_stage_1"
      incoming_topic: "$share/python/testapp/generator"
      outgoing_topic: "testapp/processor_stage_1"
      instances:
        - id: "1"
          priority: 1
          tuned_parameters:
            model: "yolov3"
            confidence: 0.5
            threshold: 0.3
        - id: "2"
          priority: 2
          tuned_parameters:
            model: "yolov3"
            confidence: 0.5
            threshold: 0.3

    - order: 2
      id_prefix: "processor_stage_2"
      incoming_topic: "$share/python/testapp/processor_stage_1"
      outgoing_topic: "testapp/processor_stage_2"
      instances:
        - id: "1"
          priority: 1
          tuned_parameters:
            param1: "test"
            param2: 0.5
        - id: "2"
          priority: 2
          tuned_parameters:
            param1: "test2"
            param2: 0.8

  distributors:
    id_prefix: "distributor"
    incoming_topic: "$share/python/testapp/processor_stage_2"
    instances:
      - id: "1"
      - id: "2"

  aggregators:
    id_prefix: "aggregator"
    instances:
      - id: "1"
        incoming_topic: "$share/python/testapp/aggregator_1"
      - id: "2"
        incoming_topic: "$share/python/testapp/aggregator_2"




